#!/usr/bin/env python
import openerp

### Peter remote debugging
#import pydevd
#pydevd.settrace('127.0.0.1', port=7999, stdoutToServer=True, stderrToServer=True)


if __name__ == "__main__":
    openerp.cli.main()

